---
title: "data-merge"
author: "Helen Simpson"
date: "9/23/2020"
output: html_document
---

```{r master.setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(include = FALSE)

#from now on, I'm going to do data merging in this .Rmd each week to make a complete dataset that I can then use in each blog post's .Rmd in order to do the week's analysis. This way I will have all variables easily accessible and I won't have to repeat code.
#for now, running this from another .Rmd is not working -- I will fix this in future!
#todo: clean state-level real income, bring in 2020 polling, national-level polling

library(tidyverse)

pop.vote <- read_csv("./popvote_1948-2016.csv")
state.vote <- read_csv("./popvote_bystate_1948-2016.csv")

economy <- read_csv("./econ.csv")
state.economy <- read_csv("./local.csv")
state.rpi <- read_csv("./total.csv")

state.polling.raw <- read_csv("./pollavg_bystate_1968-2016.csv")
polling.2020 <- read_csv("./polls_2020.csv")
```

```{r polling}
#copied from section1: observation is state, year
state.vote <- state.vote %>% 
  group_by(state) %>% arrange(year) %>% 
  mutate(prev_Rvote = dplyr::lag(R_pv2p),
         prev_Dvote = dplyr::lag(D_pv2p))
```

```{r economy, include=FALSE}
#copied from section2: observation is state, year
ec.merge.data <- state.economy %>% 
  filter(`State and area` != "Los Angeles County",
         `State and area` != "New York city") %>% 
  filter(Month %in% c("04", "05", "06")) %>% #q2 months only
  rename(state = `State and area`,
         year = Year) %>% 
  arrange(state, year) %>%  #for visual checks of averages
  group_by(state, year) %>% 
  mutate(unem.quarter.ave = (sum(Unemployed_prce))/3) %>% #calculate average unem for the quarter
  filter(Month == "04") %>% #take only one obs per quarter
  select(state, year, unem.quarter.ave)

#calculate year-on-year unemployment difference, Q2 year2 - Q2 year1
#I can only get lag() to work with group_by and arrange... not sure why
ec.merge.data <- ec.merge.data %>% group_by(state) %>% arrange(year) %>%
  mutate(unem.last = dplyr::lag(unem.quarter.ave), 
         unem.diff = unem.quarter.ave - unem.last) %>% 
  arrange(state, year) %>% #for visual checks
filter(year %in% c(1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020)) #election years only

#merge state-level unemployment and state-level results from last time
merge.data <- merge(ec.merge.data, state.vote, by = c("state", "year"), all = TRUE)

#get list of incumbent parties from national-level dataset
inc.list <- pop.vote %>% filter(incumbent_party == TRUE) %>% 
  select(year, party) %>% 
  rename(inc.party = party)

#merge state unem+vote data with incumbent list, set inc.party to two-party vote share of incumbent party
state.ec.data <- merge(merge.data, inc.list, all = TRUE) %>% 
  mutate(inc.vote = case_when(
    inc.party == "democrat" ~ D_pv2p,
    inc.party == "republican" ~ R_pv2p),
  inc.prev.vote = case_when(
    inc.party == "democrat" ~ prev_Dvote,
    inc.party == "republican" ~ prev_Rvote
    ))

#copied from section code, section2: observation is year
national.ec <- pop.vote %>% 
  filter(incumbent_party == TRUE) %>%
  select(year, winner, pv2p) %>%
  left_join(economy %>% filter(quarter == 2))

#merge state and national economic data, also state-level popular vote: observation is state, year
ec.data <- merge(state.ec.data, national.ec, all = TRUE)
```

```{r polling, echo=FALSE}

state.polling <- state.polling.raw %>% 
  select(-candidate_name, -before_convention) %>% #otherwise the spread won't match them up
  group_by(state, poll_date) %>% 
  spread(key = party, value = avg_poll) %>% 
  filter(!is.na(democrat), !is.na(republican)) %>% #we lose about 40 obs for both
  mutate(r.lead = republican - democrat)

state.polling.ave <- state.polling %>% 
  filter(days_left < 30) %>% 
  group_by(state, year) %>% 
  mutate(ave.030 = sum(r.lead)/length(r.lead)) %>% 
  select(year, state, ave.030) %>% 
  distinct()

state.polling.ave <- state.polling %>% 
  filter(30 <= days_left) %>% 
  group_by(state, year) %>% 
  mutate(ave.30plus = sum(r.lead)/length(r.lead)) %>% 
  select(year, state, ave.30plus) %>% 
  distinct() %>% 
  merge(state.polling.ave, all = TRUE)

# state.polling.ave <- state.polling %>% 
#   filter(60 <= days_left, days_left < 120) %>% 
#   group_by(state, year) %>% 
#   mutate(ave.60120 = sum(r.lead)/length(r.lead)) %>% 
#   select(year, state, ave.60120) %>% 
#   distinct() %>% 
#   merge(state.polling.ave, all = TRUE)
# 
# state.polling.ave <- state.polling %>% 
#   filter(days_left > 120) %>% 
#   group_by(state, year) %>% 
#   mutate(ave.120 = sum(r.lead)/length(r.lead)) %>% 
#   select(year, state, ave.120) %>% 
#   distinct() %>% 
#   merge(state.polling.ave, all = TRUE)

all.data <- merge(ec.data, state.polling.ave, all = TRUE)

write.csv(all.data, "./all_data.csv", row.names = FALSE)
```


