---
title: "section3"
author: "Helen Simpson"
date: "9/23/2020"
output: html_document
---

```{r setup, include=FALSE}
#### NOT RUN
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(rstanarm)
library(stargazer)
library(lme4)

my.data <- read_csv("./all_data.csv")

#it's time for the multi-level model. let's have national-level GDP and state-level real income, state-level vote last election, state level polls*time to election to predict state-level results
#vs. national-level GDP, state-level real income, state-level vote last election, national-level polls*time to election
#compare the models using r2, sample cross-validation (leave one out)
#use both models to predict 2020
#todo: read in 2020 data, read in national data + make national model, compare models (coefficients and p values), make 2020 predictions using local and state models
```

```{r}
test <- my.data %>% 
  group_by(state) %>% 
  filter(!is.na(R_pv2p), !is.na(ave.30plus)) %>% 
  do(tidy(lm(R_pv2p ~ prev_Rvote + GDP_growth_qt + ave.30plus + inc.party, data = .)))


# my.test <- test %>% filter(term == "ave.3060")
# hist(my.test$p.value)

```

```{r}
#https://stats.stackexchange[.]com/questions/164457/r-glmer-warnings-model-fails-to-converge-model-is-nearly-unidentifiable
#https://mc-stan[.]org/users/documentation/case-studies/tutorial_rstanarm.html#using-the-rstanarm-package
my.model <- stan_lmer(R_pv2p ~ GDP_growth_qt + (1 + prev_Rvote|state), data = my.data)
summary(my.model)

my.data <- my.data %>% mutate(GDP_growth_qt = GDP_growth_qt * 50)

my.like.model <- lmer(R_pv2p ~ GDP_growth_qt + inc.party + (1 + prev_Rvote + ave.30plus|state), data = my.data, REML = TRUE)
summary(my.like.model)
my.test <- data.frame(coef(my.like.model)$state[])
```

